[package]
name = "bity"
version = "0.1.0"
edition = "2021"

[features]
default = []
serde = ["dep:serde"]

[dependencies]
serde = { version = "1.0.203", features = ["derive"], optional = true }

[dev-dependencies]
toml = "0.8.14"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]